[package]
name = "habitTracker"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["clock", "serde"] }
serde = { version = "1", features = ["derive"] }
clap = { version = "4.0", features = ["derive"] }
serde_json = "1"